name: Cask Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest casks
        run: curl -o packages/brewCasks/cask.json https://formulae.brew.sh/api/cask.json

      - name: Push
        run: |
          git config user.name gh-actions
          git config user.email ci+gh@icerius.org
          git add packages/brewCasks/cask.json
          git commit -m "Update casks"
          git push
